name = "SurrealNumbers"
uuid = "26925f1b-925f-4501-bfe7-b95240cb9278"
authors = ["Jared Lumpe"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
DocStringExtensions = "0.8"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
